language: python
python:
- '2.7'
install:
- pip install -U platformio
script:
- pio --version
- pio run -e deploy -e relayboard
before_deploy:
- cd ..
- tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}.tar.gz -C ${TRAVIS_BUILD_DIR}/bin .
deploy:
  provider: releases
  api_key:
    secure: cUOCbQNHNnktb2Txa2yOFG8eBeUSPfc0E9lA156CcFqQ40tpuXsQBWpRV6n9DBz4cxU4mYSaxBVdWvu1qBkqbJl3VmKdpFm2JdN9qFsDmU9A6L02r+N5nh8O9hkc3OxKvqDa5iX7gYDyag+daY4wL6DzNCQom/o+Yks6gcHrsqmmIqDTxXgPyJsVGmTiKckABuX39eciOPN/COJDHyoKZ5IS0CjQ6HLbOGmM9eY//wtITPgNOcb3cSSSRClZ5rVC/50PpHqTR7dJ+xran0WdUhJiLB6U4/RFYr0ChAqUxYUS9Sn2lCywBPrstwsdu5lWB6sWHVCTAWyi8bO0TlJmOElVGXUJkdO2B+r8vceanEZKjKZmQXNkS0MSHl9AzGWKELUDnLtKZ93ra/lu/i8FM1Oh5/zwTVjRe6HkquHeuJaN+FMiroaR+qbWJmnkaR9ZdNsI1gGBBi0spUkj17Pk0aJYZPWIuPJeHrIc2RkBz1zzbqGPKDkRxUT3E5kU5qkuCcFaYB+scjd7vnYkTxeCSSdy5nUu1+F8pbgG1O/42tVVKa2S96loi+m4Uxgb9naTXYgCTD3t7guDu7qc1gf+P4QxJRMUgtpy4+faQnS3QPGFJuLeTeJ4UnLswqkgCMF00wG/qzMKLyS5uuqv93f/nBEmGVgPA9jWNwf1Vqb5WX0=
  file: "${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    repo: esprfid/esp-rfid
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$